name: Build Releases

on:
  workflow_dispatch:
  push:
    tags: ['v*.*.*']

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      - name: Build with PyInstaller (windows)
        run: |
          pyinstaller --onefile --add-data "template_statistika.docx;." main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      - name: Build with PyInstaller (macos)
        run: |
          pyinstaller --onefile --add-data "template_statistika.docx:." main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-exe
          path: dist/*
